DROP TABLE IF EXISTS users, request, categories, compilation_events, events, compilation, comments;

CREATE TABLE IF NOT EXISTS users
(
    user_id    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_name  VARCHAR(250)        NOT NULL,
    user_email VARCHAR(254) UNIQUE NOT NULL
);

CREATE TABLE IF NOT EXISTS categories
(
    category_id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category_name VARCHAR(50) UNIQUE NOT NULL
);

CREATE TABLE IF NOT EXISTS events
(
    event_id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_title              VARCHAR(120)                NOT NULL,
    event_annotation         VARCHAR(2000)               NOT NULL,
    event_description        VARCHAR(7000)               NOT NULL,
    event_date               TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    event_created_on         TIMESTAMP WITHOUT TIME ZONE,
    event_published_on       TIMESTAMP WITHOUT TIME ZONE,
    event_state              VARCHAR(10) DEFAULT 'PENDING',
    event_paid               BOOLEAN     DEFAULT FALSE,
    event_request_moderation BOOLEAN     DEFAULT TRUE,
    event_participant_limit  INTEGER     DEFAULT 0,
    event_location_lat       FLOAT                       NOT NULL,
    event_location_lon       FLOAT                       NOT NULL,
    event_initiator_id       BIGINT REFERENCES users (user_id) ON DELETE CASCADE,
    event_category_id        BIGINT REFERENCES categories (category_id) ON DELETE RESTRICT
);

CREATE TABLE IF NOT EXISTS compilation
(
    compilation_id     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    compilation_title  VARCHAR(50) NOT NULL,
    compilation_pinned BOOLEAN DEFAULT FALSE
);

CREATE TABLE IF NOT EXISTS compilation_events
(
    compilation_id       BIGINT REFERENCES compilation (compilation_id),
    compilation_event_id BIGINT REFERENCES events (event_id),
    PRIMARY KEY (compilation_id, compilation_event_id)
);

CREATE TABLE IF NOT EXISTS request
(
    request_id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id           BIGINT REFERENCES events (event_id),
    requester_id       BIGINT REFERENCES users (user_id),
    request_status     VARCHAR(124)                NOT NULL,
    request_created_on TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    UNIQUE (requester_id, event_id)
);

CREATE TABLE IF NOT EXISTS comments
(
    comment_id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    comment_commentator_id BIGINT REFERENCES users (user_id) ON DELETE CASCADE,
    comment_event_id       BIGINT REFERENCES events (event_id) ON DELETE CASCADE,
    comment_text           VARCHAR(1024) NOT NULL,
    comment_created_on     TIMESTAMP WITHOUT TIME ZONE
);
