version: '3.1'
services:
  stats-server:
    build: stats-service/stats-server
    image: explore-with-me:stats-server
    container_name: stats-server-container
    ports:
      - "9090:9090"
    depends_on:
      - stats-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-db:5432/stats

  stats-db:
    image: postgres:14-alpine
    container_name: stats-db-container
    ports:
      - "6541:5432"
    environment:
          - POSTGRES_DB=stats
          - POSTGRES_USER=postgres
          - POSTGRES_PASSWORD=iamroot

  ewm-service:
    build: main-service
    image: explore-with-me:main-service
    container_name: main-service-container
    ports:
      - "8080:8080"
    environment:
          - STATS_SERVER_URL=http://stats-server:9090

  ewm-db:
    image: postgres:14-alpine
    container_name: ewm-db-container
    environment:
      - POSTGRES_DB=service
      - POSTGRES_USER=ewm-postgres
      - POSTGRES_PASSWORD=iamroot
